# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: v:/vivado/Arm_ipi_repository/Vertical_Projection_char8/src/vp_ram/vp_ram.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vp_ram || ORIG_REF_NAME==vp_ram} -quiet] -quiet

# XDC: v:/vivado/Arm_ipi_repository/Vertical_Projection_char8/src/vp_ram/vp_ram_ooc.xdc
