# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: v:/vivado/Arm_ipi_repository/number_recgonize/src/digital_ram/digital_ram.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==digital_ram || ORIG_REF_NAME==digital_ram} -quiet] -quiet

# XDC: v:/vivado/Arm_ipi_repository/number_recgonize/src/digital_ram/digital_ram_ooc.xdc
