# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: V:/hardware/m3_for_arty_a7/constraints/m3_for_arty_a7.xdc

# XDC: V:/hardware/m3_for_arty_a7/constraints/m3_for_arty_a7_impl.xdc

# Block Designs: V:/hardware/m3_for_arty_a7/block_diagram/m3_for_arty_a7.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7 || ORIG_REF_NAME==m3_for_arty_a7} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_bram_ctrl_0_0/m3_for_arty_a7_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_bram_ctrl_0_0 || ORIG_REF_NAME==m3_for_arty_a7_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_gpio_1_0/m3_for_arty_a7_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_gpio_1_0 || ORIG_REF_NAME==m3_for_arty_a7_axi_gpio_1_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_interconnect_0_0/m3_for_arty_a7_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_interconnect_0_0 || ORIG_REF_NAME==m3_for_arty_a7_axi_interconnect_0_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_quad_spi_0_0/m3_for_arty_a7_axi_quad_spi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_quad_spi_0_0 || ORIG_REF_NAME==m3_for_arty_a7_axi_quad_spi_0_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_uartlite_0_0/m3_for_arty_a7_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_uartlite_0_0 || ORIG_REF_NAME==m3_for_arty_a7_axi_uartlite_0_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_blk_mem_gen_0_0/m3_for_arty_a7_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_blk_mem_gen_0_0 || ORIG_REF_NAME==m3_for_arty_a7_blk_mem_gen_0_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_xlconcat_0_0/m3_for_arty_a7_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_xlconcat_0_0 || ORIG_REF_NAME==m3_for_arty_a7_xlconcat_0_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_xlconcat_1_0/m3_for_arty_a7_xlconcat_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_xlconcat_1_0 || ORIG_REF_NAME==m3_for_arty_a7_xlconcat_1_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_xlconstant_1_0/m3_for_arty_a7_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_xlconstant_1_0 || ORIG_REF_NAME==m3_for_arty_a7_xlconstant_1_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_Cortex_M3_0_0/m3_for_arty_a7_Cortex_M3_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_Cortex_M3_0_0 || ORIG_REF_NAME==m3_for_arty_a7_Cortex_M3_0_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_interconnect_0_1/m3_for_arty_a7_axi_interconnect_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_interconnect_0_1 || ORIG_REF_NAME==m3_for_arty_a7_axi_interconnect_0_1} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_single_spi_0_0/m3_for_arty_a7_axi_single_spi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_single_spi_0_0 || ORIG_REF_NAME==m3_for_arty_a7_axi_single_spi_0_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_quad_spi_0_1/m3_for_arty_a7_axi_quad_spi_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_quad_spi_0_1 || ORIG_REF_NAME==m3_for_arty_a7_axi_quad_spi_0_1} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_xip_quad_spi_0_0/m3_for_arty_a7_axi_xip_quad_spi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_xip_quad_spi_0_0 || ORIG_REF_NAME==m3_for_arty_a7_axi_xip_quad_spi_0_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_gpio_0_1/m3_for_arty_a7_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_gpio_0_1 || ORIG_REF_NAME==m3_for_arty_a7_axi_gpio_0_1} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_protocol_convert_0_0/m3_for_arty_a7_axi_protocol_convert_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_protocol_convert_0_0 || ORIG_REF_NAME==m3_for_arty_a7_axi_protocol_convert_0_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_DAPLink_to_Arty_shield_0_0/m3_for_arty_a7_DAPLink_to_Arty_shield_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_DAPLink_to_Arty_shield_0_0 || ORIG_REF_NAME==m3_for_arty_a7_DAPLink_to_Arty_shield_0_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_xbar_0/m3_for_arty_a7_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_xbar_0 || ORIG_REF_NAME==m3_for_arty_a7_xbar_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_xbar_1/m3_for_arty_a7_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_xbar_1 || ORIG_REF_NAME==m3_for_arty_a7_xbar_1} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_proc_sys_reset_DAPLink_0/m3_for_arty_a7_proc_sys_reset_DAPLink_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_proc_sys_reset_DAPLink_0 || ORIG_REF_NAME==m3_for_arty_a7_proc_sys_reset_DAPLink_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_proc_sys_reset_base_0/m3_for_arty_a7_proc_sys_reset_base_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_proc_sys_reset_base_0 || ORIG_REF_NAME==m3_for_arty_a7_proc_sys_reset_base_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_i_interconnect_aresetn_0/m3_for_arty_a7_i_interconnect_aresetn_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_i_interconnect_aresetn_0 || ORIG_REF_NAME==m3_for_arty_a7_i_interconnect_aresetn_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_i_peripheral_aresetn1_0/m3_for_arty_a7_i_peripheral_aresetn1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_i_peripheral_aresetn1_0 || ORIG_REF_NAME==m3_for_arty_a7_i_peripheral_aresetn1_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_i_sysresetn_or_0/m3_for_arty_a7_i_sysresetn_or_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_i_sysresetn_or_0 || ORIG_REF_NAME==m3_for_arty_a7_i_sysresetn_or_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_i_inv_dbgresetn_0/m3_for_arty_a7_i_inv_dbgresetn_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_i_inv_dbgresetn_0 || ORIG_REF_NAME==m3_for_arty_a7_i_inv_dbgresetn_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_i_inv_sysresetn1_0/m3_for_arty_a7_i_inv_sysresetn1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_i_inv_sysresetn1_0 || ORIG_REF_NAME==m3_for_arty_a7_i_inv_sysresetn1_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_clk_wiz_0_0/m3_for_arty_a7_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_clk_wiz_0_0 || ORIG_REF_NAME==m3_for_arty_a7_clk_wiz_0_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_xlconstant_1_1/m3_for_arty_a7_xlconstant_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_xlconstant_1_1 || ORIG_REF_NAME==m3_for_arty_a7_xlconstant_1_1} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_v_vid_in_axi4s_0_0/m3_for_arty_a7_v_vid_in_axi4s_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_v_vid_in_axi4s_0_0 || ORIG_REF_NAME==m3_for_arty_a7_v_vid_in_axi4s_0_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_v_axi4s_vid_out_0_0/m3_for_arty_a7_v_axi4s_vid_out_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==m3_for_arty_a7_v_axi4s_vid_out_0_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_vdma_0_0/m3_for_arty_a7_axi_vdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_vdma_0_0 || ORIG_REF_NAME==m3_for_arty_a7_axi_vdma_0_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_OV_Sensor_ML_2_1/m3_for_arty_a7_OV_Sensor_ML_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_OV_Sensor_ML_2_1 || ORIG_REF_NAME==m3_for_arty_a7_OV_Sensor_ML_2_1} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_v_tc_0_0/m3_for_arty_a7_v_tc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_v_tc_0_0 || ORIG_REF_NAME==m3_for_arty_a7_v_tc_0_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_xlconstant_0_0/m3_for_arty_a7_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_xlconstant_0_0 || ORIG_REF_NAME==m3_for_arty_a7_xlconstant_0_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_proc_sys_reset_0_0/m3_for_arty_a7_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_proc_sys_reset_0_0 || ORIG_REF_NAME==m3_for_arty_a7_proc_sys_reset_0_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/m3_for_arty_a7_smartconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_smartconnect_0_0 || ORIG_REF_NAME==m3_for_arty_a7_smartconnect_0_0} -quiet] -quiet

# Block Designs: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/bd_0834.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_12/bd_0834_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_18/bd_0834_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_25/bd_0834_s02a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_31/bd_0834_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_37/bd_0834_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_32/bd_0834_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_33/bd_0834_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_34/bd_0834_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_35/bd_0834_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_36/bd_0834_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_26/bd_0834_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_27/bd_0834_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_28/bd_0834_sawn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_29/bd_0834_swn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_30/bd_0834_sbn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_22/bd_0834_s02mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_23/bd_0834_s02tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_24/bd_0834_s02sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_19/bd_0834_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_20/bd_0834_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_21/bd_0834_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_15/bd_0834_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_16/bd_0834_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_17/bd_0834_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_13/bd_0834_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_14/bd_0834_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_9/bd_0834_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_10/bd_0834_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_11/bd_0834_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_4/bd_0834_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_5/bd_0834_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_6/bd_0834_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_7/bd_0834_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_8/bd_0834_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_0/bd_0834_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_1/bd_0834_psr0_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_2/bd_0834_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_3/bd_0834_psr_aclk1_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_rgb2vga_0_0/m3_for_arty_a7_rgb2vga_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_rgb2vga_0_0 || ORIG_REF_NAME==m3_for_arty_a7_rgb2vga_0_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_mig_7series_0_2 || ORIG_REF_NAME==m3_for_arty_a7_mig_7series_0_2} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_xlconstant_0_2/m3_for_arty_a7_xlconstant_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_xlconstant_0_2 || ORIG_REF_NAME==m3_for_arty_a7_xlconstant_0_2} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_I2C_OV5640_Init_RGB5_0_0/m3_for_arty_a7_I2C_OV5640_Init_RGB5_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_I2C_OV5640_Init_RGB5_0_0 || ORIG_REF_NAME==m3_for_arty_a7_I2C_OV5640_Init_RGB5_0_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_rgb_change_0_0/m3_for_arty_a7_rgb_change_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_rgb_change_0_0 || ORIG_REF_NAME==m3_for_arty_a7_rgb_change_0_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_sync_change_0_0/m3_for_arty_a7_sync_change_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_sync_change_0_0 || ORIG_REF_NAME==m3_for_arty_a7_sync_change_0_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_HVcount_0_0/m3_for_arty_a7_HVcount_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_HVcount_0_0 || ORIG_REF_NAME==m3_for_arty_a7_HVcount_0_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_rgb2ycbcr_0_0/m3_for_arty_a7_rgb2ycbcr_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_rgb2ycbcr_0_0 || ORIG_REF_NAME==m3_for_arty_a7_rgb2ycbcr_0_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_car_id_0_0/m3_for_arty_a7_car_id_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_car_id_0_0 || ORIG_REF_NAME==m3_for_arty_a7_car_id_0_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_Vertical_Projection_0_0/m3_for_arty_a7_Vertical_Projection_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_Vertical_Projection_0_0 || ORIG_REF_NAME==m3_for_arty_a7_Vertical_Projection_0_0} -quiet] -quiet

# IP: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_Vertical_Projection_0_0/src/vpro_ram/vpro_ram.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vpro_ram || ORIG_REF_NAME==vpro_ram} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_capture_lpr_0_0/m3_for_arty_a7_capture_lpr_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_capture_lpr_0_0 || ORIG_REF_NAME==m3_for_arty_a7_capture_lpr_0_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_rgb2ycbcr_1_0/m3_for_arty_a7_rgb2ycbcr_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_rgb2ycbcr_1_0 || ORIG_REF_NAME==m3_for_arty_a7_rgb2ycbcr_1_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_ycbcr_location_0_0/m3_for_arty_a7_ycbcr_location_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_ycbcr_location_0_0 || ORIG_REF_NAME==m3_for_arty_a7_ycbcr_location_0_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_HVcount_1_0/m3_for_arty_a7_HVcount_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_HVcount_1_0 || ORIG_REF_NAME==m3_for_arty_a7_HVcount_1_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_Vertical_Projection8_0_0/m3_for_arty_a7_Vertical_Projection8_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_Vertical_Projection8_0_0 || ORIG_REF_NAME==m3_for_arty_a7_Vertical_Projection8_0_0} -quiet] -quiet

# IP: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_Vertical_Projection8_0_0/src/vp_ram/vp_ram.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vp_ram || ORIG_REF_NAME==vp_ram} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_display_0_0/m3_for_arty_a7_display_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_display_0_0 || ORIG_REF_NAME==m3_for_arty_a7_display_0_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_rgb_mux_0_0/m3_for_arty_a7_rgb_mux_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_rgb_mux_0_0 || ORIG_REF_NAME==m3_for_arty_a7_rgb_mux_0_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_sync_change_1_0/m3_for_arty_a7_sync_change_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_sync_change_1_0 || ORIG_REF_NAME==m3_for_arty_a7_sync_change_1_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_gpio_0_0/m3_for_arty_a7_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_gpio_0_0 || ORIG_REF_NAME==m3_for_arty_a7_axi_gpio_0_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_capture_single_0_1/m3_for_arty_a7_capture_single_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_capture_single_0_1 || ORIG_REF_NAME==m3_for_arty_a7_capture_single_0_1} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_char_recongize_5thing_0_0/m3_for_arty_a7_char_recongize_5thing_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_char_recongize_5thing_0_0 || ORIG_REF_NAME==m3_for_arty_a7_char_recongize_5thing_0_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_digital_recognition_0_0/m3_for_arty_a7_digital_recognition_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_digital_recognition_0_0 || ORIG_REF_NAME==m3_for_arty_a7_digital_recognition_0_0} -quiet] -quiet

# IP: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_digital_recognition_0_0/src/digital_ram/digital_ram.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==digital_ram || ORIG_REF_NAME==digital_ram} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_xlconcat_0_1/m3_for_arty_a7_xlconcat_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_xlconcat_0_1 || ORIG_REF_NAME==m3_for_arty_a7_xlconcat_0_1} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_display_lpr_boundary_0_0/m3_for_arty_a7_display_lpr_boundary_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_display_lpr_boundary_0_0 || ORIG_REF_NAME==m3_for_arty_a7_display_lpr_boundary_0_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_send_line_data_0_0/m3_for_arty_a7_send_line_data_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_send_line_data_0_0 || ORIG_REF_NAME==m3_for_arty_a7_send_line_data_0_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_capture_single_0_4/m3_for_arty_a7_capture_single_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_capture_single_0_4 || ORIG_REF_NAME==m3_for_arty_a7_capture_single_0_4} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_digital_recognition_0_4/m3_for_arty_a7_digital_recognition_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_digital_recognition_0_4 || ORIG_REF_NAME==m3_for_arty_a7_digital_recognition_0_4} -quiet] -quiet

# IP: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_digital_recognition_0_4/src/digital_ram/digital_ram.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==digital_ram || ORIG_REF_NAME==digital_ram} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_xlconcat_0_5/m3_for_arty_a7_xlconcat_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_xlconcat_0_5 || ORIG_REF_NAME==m3_for_arty_a7_xlconcat_0_5} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_capture_single_0_3/m3_for_arty_a7_capture_single_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_capture_single_0_3 || ORIG_REF_NAME==m3_for_arty_a7_capture_single_0_3} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_digital_recognition_0_3/m3_for_arty_a7_digital_recognition_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_digital_recognition_0_3 || ORIG_REF_NAME==m3_for_arty_a7_digital_recognition_0_3} -quiet] -quiet

# IP: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_digital_recognition_0_3/src/digital_ram/digital_ram.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==digital_ram || ORIG_REF_NAME==digital_ram} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_xlconcat_0_4/m3_for_arty_a7_xlconcat_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_xlconcat_0_4 || ORIG_REF_NAME==m3_for_arty_a7_xlconcat_0_4} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_capture_single_0_2/m3_for_arty_a7_capture_single_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_capture_single_0_2 || ORIG_REF_NAME==m3_for_arty_a7_capture_single_0_2} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_digital_recognition_0_2/m3_for_arty_a7_digital_recognition_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_digital_recognition_0_2 || ORIG_REF_NAME==m3_for_arty_a7_digital_recognition_0_2} -quiet] -quiet

# IP: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_digital_recognition_0_2/src/digital_ram/digital_ram.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==digital_ram || ORIG_REF_NAME==digital_ram} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_xlconcat_0_3/m3_for_arty_a7_xlconcat_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_xlconcat_0_3 || ORIG_REF_NAME==m3_for_arty_a7_xlconcat_0_3} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_capture_single_0_0/m3_for_arty_a7_capture_single_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_capture_single_0_0 || ORIG_REF_NAME==m3_for_arty_a7_capture_single_0_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_digital_recognition_0_1/m3_for_arty_a7_digital_recognition_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_digital_recognition_0_1 || ORIG_REF_NAME==m3_for_arty_a7_digital_recognition_0_1} -quiet] -quiet

# IP: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_digital_recognition_0_1/src/digital_ram/digital_ram.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==digital_ram || ORIG_REF_NAME==digital_ram} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_xlconcat_0_2/m3_for_arty_a7_xlconcat_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_xlconcat_0_2 || ORIG_REF_NAME==m3_for_arty_a7_xlconcat_0_2} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_gpio_0_2/m3_for_arty_a7_axi_gpio_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_gpio_0_2 || ORIG_REF_NAME==m3_for_arty_a7_axi_gpio_0_2} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_quad_spi_1_0/m3_for_arty_a7_axi_quad_spi_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_quad_spi_1_0 || ORIG_REF_NAME==m3_for_arty_a7_axi_quad_spi_1_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_Hcount_Send_0_0/m3_for_arty_a7_Hcount_Send_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_Hcount_Send_0_0 || ORIG_REF_NAME==m3_for_arty_a7_Hcount_Send_0_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_binary_image_etch_0_2/m3_for_arty_a7_binary_image_etch_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_binary_image_etch_0_2 || ORIG_REF_NAME==m3_for_arty_a7_binary_image_etch_0_2} -quiet] -quiet

# IP: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_binary_image_etch_0_2/src/img_ram/img_ram.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==img_ram || ORIG_REF_NAME==img_ram} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_binary_image_swell_0_2/m3_for_arty_a7_binary_image_swell_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_binary_image_swell_0_2 || ORIG_REF_NAME==m3_for_arty_a7_binary_image_swell_0_2} -quiet] -quiet

# IP: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_binary_image_swell_0_2/src/img_ram/img_ram.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==img_ram || ORIG_REF_NAME==img_ram} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_binary_image_etch_0_1/m3_for_arty_a7_binary_image_etch_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_binary_image_etch_0_1 || ORIG_REF_NAME==m3_for_arty_a7_binary_image_etch_0_1} -quiet] -quiet

# IP: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_binary_image_etch_0_1/src/img_ram/img_ram.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==img_ram || ORIG_REF_NAME==img_ram} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_binary_image_etch_1_2/m3_for_arty_a7_binary_image_etch_1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_binary_image_etch_1_2 || ORIG_REF_NAME==m3_for_arty_a7_binary_image_etch_1_2} -quiet] -quiet

# IP: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_binary_image_etch_1_2/src/img_ram/img_ram.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==img_ram || ORIG_REF_NAME==img_ram} -quiet] -quiet

# IP: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_auto_pc_11/m3_for_arty_a7_auto_pc_11.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_auto_pc_11 || ORIG_REF_NAME==m3_for_arty_a7_auto_pc_11} -quiet] -quiet

# IP: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_auto_pc_10/m3_for_arty_a7_auto_pc_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_auto_pc_10 || ORIG_REF_NAME==m3_for_arty_a7_auto_pc_10} -quiet] -quiet

# IP: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_auto_pc_9/m3_for_arty_a7_auto_pc_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_auto_pc_9 || ORIG_REF_NAME==m3_for_arty_a7_auto_pc_9} -quiet] -quiet

# IP: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_auto_pc_8/m3_for_arty_a7_auto_pc_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_auto_pc_8 || ORIG_REF_NAME==m3_for_arty_a7_auto_pc_8} -quiet] -quiet

# IP: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_auto_pc_7/m3_for_arty_a7_auto_pc_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_auto_pc_7 || ORIG_REF_NAME==m3_for_arty_a7_auto_pc_7} -quiet] -quiet

# IP: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_auto_pc_6/m3_for_arty_a7_auto_pc_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_auto_pc_6 || ORIG_REF_NAME==m3_for_arty_a7_auto_pc_6} -quiet] -quiet

# IP: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_auto_pc_5/m3_for_arty_a7_auto_pc_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_auto_pc_5 || ORIG_REF_NAME==m3_for_arty_a7_auto_pc_5} -quiet] -quiet

# IP: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_auto_pc_4/m3_for_arty_a7_auto_pc_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_auto_pc_4 || ORIG_REF_NAME==m3_for_arty_a7_auto_pc_4} -quiet] -quiet

# IP: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_auto_pc_3/m3_for_arty_a7_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_auto_pc_3 || ORIG_REF_NAME==m3_for_arty_a7_auto_pc_3} -quiet] -quiet

# IP: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_auto_pc_2/m3_for_arty_a7_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_auto_pc_2 || ORIG_REF_NAME==m3_for_arty_a7_auto_pc_2} -quiet] -quiet

# IP: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_auto_pc_1/m3_for_arty_a7_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_auto_pc_1 || ORIG_REF_NAME==m3_for_arty_a7_auto_pc_1} -quiet] -quiet

# IP: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_auto_pc_0/m3_for_arty_a7_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_auto_pc_0 || ORIG_REF_NAME==m3_for_arty_a7_auto_pc_0} -quiet] -quiet

# IP: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_auto_pc_12/m3_for_arty_a7_auto_pc_12.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_auto_pc_12 || ORIG_REF_NAME==m3_for_arty_a7_auto_pc_12} -quiet] -quiet

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_gpio_1_0/m3_for_arty_a7_axi_gpio_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_gpio_1_0 || ORIG_REF_NAME==m3_for_arty_a7_axi_gpio_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_gpio_1_0/m3_for_arty_a7_axi_gpio_1_0_ooc.xdc

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_gpio_1_0/m3_for_arty_a7_axi_gpio_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_gpio_1_0 || ORIG_REF_NAME==m3_for_arty_a7_axi_gpio_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_quad_spi_0_0/m3_for_arty_a7_axi_quad_spi_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_quad_spi_0_0 || ORIG_REF_NAME==m3_for_arty_a7_axi_quad_spi_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_quad_spi_0_0/m3_for_arty_a7_axi_quad_spi_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_quad_spi_0_0 || ORIG_REF_NAME==m3_for_arty_a7_axi_quad_spi_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_quad_spi_0_0/m3_for_arty_a7_axi_quad_spi_0_0_ooc.xdc

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_quad_spi_0_0/m3_for_arty_a7_axi_quad_spi_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_quad_spi_0_0 || ORIG_REF_NAME==m3_for_arty_a7_axi_quad_spi_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_uartlite_0_0/m3_for_arty_a7_axi_uartlite_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_uartlite_0_0 || ORIG_REF_NAME==m3_for_arty_a7_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_uartlite_0_0/m3_for_arty_a7_axi_uartlite_0_0_ooc.xdc

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_uartlite_0_0/m3_for_arty_a7_axi_uartlite_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_uartlite_0_0 || ORIG_REF_NAME==m3_for_arty_a7_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_blk_mem_gen_0_0/m3_for_arty_a7_blk_mem_gen_0_0_ooc.xdc

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_Cortex_M3_0_0/m3_for_arty_a7_Cortex_M3_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_Cortex_M3_0_0 || ORIG_REF_NAME==m3_for_arty_a7_Cortex_M3_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_single_spi_0_0/m3_for_arty_a7_axi_single_spi_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_single_spi_0_0 || ORIG_REF_NAME==m3_for_arty_a7_axi_single_spi_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_single_spi_0_0/m3_for_arty_a7_axi_single_spi_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_single_spi_0_0 || ORIG_REF_NAME==m3_for_arty_a7_axi_single_spi_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_single_spi_0_0/m3_for_arty_a7_axi_single_spi_0_0_ooc.xdc

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_single_spi_0_0/m3_for_arty_a7_axi_single_spi_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_single_spi_0_0 || ORIG_REF_NAME==m3_for_arty_a7_axi_single_spi_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_quad_spi_0_1/m3_for_arty_a7_axi_quad_spi_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_quad_spi_0_1 || ORIG_REF_NAME==m3_for_arty_a7_axi_quad_spi_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_quad_spi_0_1/m3_for_arty_a7_axi_quad_spi_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_quad_spi_0_1 || ORIG_REF_NAME==m3_for_arty_a7_axi_quad_spi_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_quad_spi_0_1/m3_for_arty_a7_axi_quad_spi_0_1_ooc.xdc

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_quad_spi_0_1/m3_for_arty_a7_axi_quad_spi_0_1_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_quad_spi_0_1 || ORIG_REF_NAME==m3_for_arty_a7_axi_quad_spi_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_xip_quad_spi_0_0/m3_for_arty_a7_axi_xip_quad_spi_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_xip_quad_spi_0_0 || ORIG_REF_NAME==m3_for_arty_a7_axi_xip_quad_spi_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_xip_quad_spi_0_0/m3_for_arty_a7_axi_xip_quad_spi_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_xip_quad_spi_0_0 || ORIG_REF_NAME==m3_for_arty_a7_axi_xip_quad_spi_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_xip_quad_spi_0_0/m3_for_arty_a7_axi_xip_quad_spi_0_0_ooc.xdc

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_xip_quad_spi_0_0/m3_for_arty_a7_axi_xip_quad_spi_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_xip_quad_spi_0_0 || ORIG_REF_NAME==m3_for_arty_a7_axi_xip_quad_spi_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_gpio_0_1/m3_for_arty_a7_axi_gpio_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_gpio_0_1 || ORIG_REF_NAME==m3_for_arty_a7_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_gpio_0_1/m3_for_arty_a7_axi_gpio_0_1_ooc.xdc

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_gpio_0_1/m3_for_arty_a7_axi_gpio_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_gpio_0_1 || ORIG_REF_NAME==m3_for_arty_a7_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_protocol_convert_0_0/m3_for_arty_a7_axi_protocol_convert_0_0_ooc.xdc

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_proc_sys_reset_DAPLink_0/m3_for_arty_a7_proc_sys_reset_DAPLink_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_proc_sys_reset_DAPLink_0 || ORIG_REF_NAME==m3_for_arty_a7_proc_sys_reset_DAPLink_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_proc_sys_reset_DAPLink_0/m3_for_arty_a7_proc_sys_reset_DAPLink_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_proc_sys_reset_DAPLink_0 || ORIG_REF_NAME==m3_for_arty_a7_proc_sys_reset_DAPLink_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_proc_sys_reset_base_0/m3_for_arty_a7_proc_sys_reset_base_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_proc_sys_reset_base_0 || ORIG_REF_NAME==m3_for_arty_a7_proc_sys_reset_base_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_proc_sys_reset_base_0/m3_for_arty_a7_proc_sys_reset_base_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_proc_sys_reset_base_0 || ORIG_REF_NAME==m3_for_arty_a7_proc_sys_reset_base_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_clk_wiz_0_0/m3_for_arty_a7_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_clk_wiz_0_0 || ORIG_REF_NAME==m3_for_arty_a7_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_clk_wiz_0_0/m3_for_arty_a7_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_clk_wiz_0_0 || ORIG_REF_NAME==m3_for_arty_a7_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_clk_wiz_0_0/m3_for_arty_a7_clk_wiz_0_0_late.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_clk_wiz_0_0 || ORIG_REF_NAME==m3_for_arty_a7_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_clk_wiz_0_0/m3_for_arty_a7_clk_wiz_0_0_ooc.xdc

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_v_vid_in_axi4s_0_0/m3_for_arty_a7_v_vid_in_axi4s_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_v_vid_in_axi4s_0_0 || ORIG_REF_NAME==m3_for_arty_a7_v_vid_in_axi4s_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_v_axi4s_vid_out_0_0/m3_for_arty_a7_v_axi4s_vid_out_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==m3_for_arty_a7_v_axi4s_vid_out_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_vdma_0_0/m3_for_arty_a7_axi_vdma_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_vdma_0_0 || ORIG_REF_NAME==m3_for_arty_a7_axi_vdma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_vdma_0_0/m3_for_arty_a7_axi_vdma_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_vdma_0_0 || ORIG_REF_NAME==m3_for_arty_a7_axi_vdma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_vdma_0_0/m3_for_arty_a7_axi_vdma_0_0_ooc.xdc

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_v_tc_0_0/m3_for_arty_a7_v_tc_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_v_tc_0_0 || ORIG_REF_NAME==m3_for_arty_a7_v_tc_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_proc_sys_reset_0_0/m3_for_arty_a7_proc_sys_reset_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_proc_sys_reset_0_0 || ORIG_REF_NAME==m3_for_arty_a7_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_proc_sys_reset_0_0/m3_for_arty_a7_proc_sys_reset_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_proc_sys_reset_0_0 || ORIG_REF_NAME==m3_for_arty_a7_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_12/bd_0834_s00a2s_0_ooc.xdc

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_18/bd_0834_s01a2s_0_ooc.xdc

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_25/bd_0834_s02a2s_0_ooc.xdc

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_31/bd_0834_m00s2a_0_ooc.xdc

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_32/bd_0834_m00arn_0_ooc.xdc

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_33/bd_0834_m00rn_0_ooc.xdc

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_34/bd_0834_m00awn_0_ooc.xdc

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_35/bd_0834_m00wn_0_ooc.xdc

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_36/bd_0834_m00bn_0_ooc.xdc

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_26/bd_0834_sarn_1_ooc.xdc

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_27/bd_0834_srn_1_ooc.xdc

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_28/bd_0834_sawn_1_ooc.xdc

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_29/bd_0834_swn_1_ooc.xdc

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_30/bd_0834_sbn_1_ooc.xdc

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_19/bd_0834_sawn_0_ooc.xdc

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_20/bd_0834_swn_0_ooc.xdc

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_21/bd_0834_sbn_0_ooc.xdc

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_13/bd_0834_sarn_0_ooc.xdc

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_14/bd_0834_srn_0_ooc.xdc

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_4/bd_0834_arsw_0_ooc.xdc

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_5/bd_0834_rsw_0_ooc.xdc

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_6/bd_0834_awsw_0_ooc.xdc

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_7/bd_0834_wsw_0_ooc.xdc

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_8/bd_0834_bsw_0_ooc.xdc

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_1/bd_0834_psr0_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_1/bd_0834_psr0_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_2/bd_0834_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_2/bd_0834_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_3/bd_0834_psr_aclk1_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_3/bd_0834_psr_aclk1_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/ooc.xdc

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/constraints/m3_for_arty_a7_mig_7series_0_2.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_mig_7series_0_2 || ORIG_REF_NAME==m3_for_arty_a7_mig_7series_0_2} -quiet] -quiet

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/constraints/m3_for_arty_a7_mig_7series_0_2_ooc.xdc

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_Vertical_Projection_0_0/src/vpro_ram/vpro_ram_ooc.xdc

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_Vertical_Projection8_0_0/src/vp_ram/vp_ram_ooc.xdc

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_gpio_0_0/m3_for_arty_a7_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_gpio_0_0 || ORIG_REF_NAME==m3_for_arty_a7_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_gpio_0_0/m3_for_arty_a7_axi_gpio_0_0_ooc.xdc

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_gpio_0_0/m3_for_arty_a7_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_gpio_0_0 || ORIG_REF_NAME==m3_for_arty_a7_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_digital_recognition_0_0/src/digital_ram/digital_ram_ooc.xdc

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_digital_recognition_0_4/src/digital_ram/digital_ram_ooc.xdc

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_digital_recognition_0_3/src/digital_ram/digital_ram_ooc.xdc

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_digital_recognition_0_2/src/digital_ram/digital_ram_ooc.xdc

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_digital_recognition_0_1/src/digital_ram/digital_ram_ooc.xdc

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_gpio_0_2/m3_for_arty_a7_axi_gpio_0_2_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_gpio_0_2 || ORIG_REF_NAME==m3_for_arty_a7_axi_gpio_0_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_gpio_0_2/m3_for_arty_a7_axi_gpio_0_2_ooc.xdc

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_gpio_0_2/m3_for_arty_a7_axi_gpio_0_2.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_gpio_0_2 || ORIG_REF_NAME==m3_for_arty_a7_axi_gpio_0_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_quad_spi_1_0/m3_for_arty_a7_axi_quad_spi_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_quad_spi_1_0 || ORIG_REF_NAME==m3_for_arty_a7_axi_quad_spi_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_quad_spi_1_0/m3_for_arty_a7_axi_quad_spi_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_quad_spi_1_0 || ORIG_REF_NAME==m3_for_arty_a7_axi_quad_spi_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_quad_spi_1_0/m3_for_arty_a7_axi_quad_spi_1_0_ooc.xdc

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_quad_spi_1_0/m3_for_arty_a7_axi_quad_spi_1_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_quad_spi_1_0 || ORIG_REF_NAME==m3_for_arty_a7_axi_quad_spi_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_binary_image_etch_0_2/src/img_ram/img_ram_ooc.xdc

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_binary_image_swell_0_2/src/img_ram/img_ram_ooc.xdc

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_binary_image_etch_0_1/src/img_ram/img_ram_ooc.xdc

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_binary_image_etch_1_2/src/img_ram/img_ram_ooc.xdc

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_auto_pc_11/m3_for_arty_a7_auto_pc_11_ooc.xdc

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_auto_pc_10/m3_for_arty_a7_auto_pc_10_ooc.xdc

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_auto_pc_9/m3_for_arty_a7_auto_pc_9_ooc.xdc

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_auto_pc_8/m3_for_arty_a7_auto_pc_8_ooc.xdc

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_auto_pc_7/m3_for_arty_a7_auto_pc_7_ooc.xdc

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_auto_pc_6/m3_for_arty_a7_auto_pc_6_ooc.xdc

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_auto_pc_5/m3_for_arty_a7_auto_pc_5_ooc.xdc

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_auto_pc_4/m3_for_arty_a7_auto_pc_4_ooc.xdc

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_auto_pc_3/m3_for_arty_a7_auto_pc_3_ooc.xdc

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_auto_pc_2/m3_for_arty_a7_auto_pc_2_ooc.xdc

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_auto_pc_1/m3_for_arty_a7_auto_pc_1_ooc.xdc

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_auto_pc_0/m3_for_arty_a7_auto_pc_0_ooc.xdc

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_auto_pc_12/m3_for_arty_a7_auto_pc_12_ooc.xdc

# XDC: V:/hardware/m3_for_arty_a7/block_diagram/m3_for_arty_a7_ooc.xdc
