# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir V:/hardware/m3_for_arty_a7/m3_for_arty_a7/m3_for_arty_a7.cache/wt [current_project]
set_property parent.project_path V:/hardware/m3_for_arty_a7/m3_for_arty_a7/m3_for_arty_a7.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys-a7-100t:part0:1.0 [current_project]
set_property ip_repo_paths {
  v:/hardware/m3_for_arty_a7/ip_repo/Hcount_Send_1.0
  v:/hardware/m3_for_arty_a7/ip_repo/Hcount_Send_1.0
  v:/hardware/m3_for_arty_a7/ip_repo/send_line_data_1.0
  v:/hardware/m3_for_arty_a7/ip_repo/char_recongize_5thing_1.0
  v:/hardware/m3_for_arty_a7/ip_repo/char_5_1.0
  v:/hardware/m3_for_arty_a7/ip_repo/one_char_read_40bit_1.0
  v:/vivado/Arm_ipi_repository
} [current_project]
set_property ip_output_repo v:/hardware/m3_for_arty_a7/m3_for_arty_a7/m3_for_arty_a7.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_mem V:/hardware/m3_for_arty_a7/m3_for_arty_a7/bram_a7.hex
read_verilog -library xil_defaultlib {
  V:/vivado/Arm_ipi_repository/new/cmos_decode.v
  V:/vivado/Arm_ipi_repository/new/count_reset.v
  V:/vivado/Arm_ipi_repository/new/OV_Sensor_ML.v
  V:/vivado/Arm_ipi_repository/cmos_i2c_oVxxxx/I2C_Controller.v
  V:/vivado/Arm_ipi_repository/cmos_i2c_oVxxxx/I2C_OV5640_RGB565_Config.v
  V:/vivado/Arm_ipi_repository/cmos_i2c_oVxxxx/I2C_OV5640_Init_RGB565.v
  V:/hardware/m3_for_arty_a7/m3_for_arty_a7/m3_for_arty_a7.srcs/sources_1/imports/new/rgb_change.v
  V:/hardware/m3_for_arty_a7/m3_for_arty_a7/m3_for_arty_a7.srcs/sources_1/imports/new/sync_change.v
  V:/hardware/m3_for_arty_a7/m3_for_arty_a7/m3_for_arty_a7.srcs/sources_1/imports/sim/HVcount.v
  V:/hardware/m3_for_arty_a7/m3_for_arty_a7/m3_for_arty_a7.srcs/sources_1/imports/sim/capture_single.v
  V:/hardware/m3_for_arty_a7/m3_for_arty_a7/m3_for_arty_a7.srcs/sources_1/imports/new/display_lpr_boundary.v
  V:/hardware/m3_for_arty_a7/block_diagram/hdl/m3_for_arty_a7_wrapper.v
}
add_files V:/hardware/m3_for_arty_a7/block_diagram/m3_for_arty_a7.bd
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_gpio_1_0/m3_for_arty_a7_axi_gpio_1_0_board.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_gpio_1_0/m3_for_arty_a7_axi_gpio_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_gpio_1_0/m3_for_arty_a7_axi_gpio_1_0.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_quad_spi_0_0/m3_for_arty_a7_axi_quad_spi_0_0_board.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_quad_spi_0_0/m3_for_arty_a7_axi_quad_spi_0_0.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_quad_spi_0_0/m3_for_arty_a7_axi_quad_spi_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_quad_spi_0_0/m3_for_arty_a7_axi_quad_spi_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_uartlite_0_0/m3_for_arty_a7_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_uartlite_0_0/m3_for_arty_a7_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_uartlite_0_0/m3_for_arty_a7_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_blk_mem_gen_0_0/m3_for_arty_a7_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_Cortex_M3_0_0/m3_for_arty_a7_Cortex_M3_0_0.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_single_spi_0_0/m3_for_arty_a7_axi_single_spi_0_0_board.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_single_spi_0_0/m3_for_arty_a7_axi_single_spi_0_0.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_single_spi_0_0/m3_for_arty_a7_axi_single_spi_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_single_spi_0_0/m3_for_arty_a7_axi_single_spi_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_quad_spi_0_1/m3_for_arty_a7_axi_quad_spi_0_1_board.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_quad_spi_0_1/m3_for_arty_a7_axi_quad_spi_0_1.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_quad_spi_0_1/m3_for_arty_a7_axi_quad_spi_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_quad_spi_0_1/m3_for_arty_a7_axi_quad_spi_0_1_clocks.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_xip_quad_spi_0_0/m3_for_arty_a7_axi_xip_quad_spi_0_0_board.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_xip_quad_spi_0_0/m3_for_arty_a7_axi_xip_quad_spi_0_0.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_xip_quad_spi_0_0/m3_for_arty_a7_axi_xip_quad_spi_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_xip_quad_spi_0_0/m3_for_arty_a7_axi_xip_quad_spi_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_gpio_0_1/m3_for_arty_a7_axi_gpio_0_1_board.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_gpio_0_1/m3_for_arty_a7_axi_gpio_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_gpio_0_1/m3_for_arty_a7_axi_gpio_0_1.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_protocol_convert_0_0/m3_for_arty_a7_axi_protocol_convert_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_proc_sys_reset_DAPLink_0/m3_for_arty_a7_proc_sys_reset_DAPLink_0_board.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_proc_sys_reset_DAPLink_0/m3_for_arty_a7_proc_sys_reset_DAPLink_0.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_proc_sys_reset_base_0/m3_for_arty_a7_proc_sys_reset_base_0_board.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_proc_sys_reset_base_0/m3_for_arty_a7_proc_sys_reset_base_0.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_clk_wiz_0_0/m3_for_arty_a7_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_clk_wiz_0_0/m3_for_arty_a7_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_clk_wiz_0_0/m3_for_arty_a7_clk_wiz_0_0_late.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_clk_wiz_0_0/m3_for_arty_a7_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_v_vid_in_axi4s_0_0/m3_for_arty_a7_v_vid_in_axi4s_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_v_axi4s_vid_out_0_0/m3_for_arty_a7_v_axi4s_vid_out_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_vdma_0_0/m3_for_arty_a7_axi_vdma_0_0.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_vdma_0_0/m3_for_arty_a7_axi_vdma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_vdma_0_0/m3_for_arty_a7_axi_vdma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_v_tc_0_0/m3_for_arty_a7_v_tc_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_proc_sys_reset_0_0/m3_for_arty_a7_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_proc_sys_reset_0_0/m3_for_arty_a7_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_12/bd_0834_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_18/bd_0834_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_25/bd_0834_s02a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_31/bd_0834_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_32/bd_0834_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_33/bd_0834_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_34/bd_0834_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_35/bd_0834_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_36/bd_0834_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_26/bd_0834_sarn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_27/bd_0834_srn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_28/bd_0834_sawn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_29/bd_0834_swn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_30/bd_0834_sbn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_19/bd_0834_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_20/bd_0834_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_21/bd_0834_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_13/bd_0834_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_14/bd_0834_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_4/bd_0834_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_5/bd_0834_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_6/bd_0834_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_7/bd_0834_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_8/bd_0834_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_1/bd_0834_psr0_0_board.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_1/bd_0834_psr0_0.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_2/bd_0834_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_2/bd_0834_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_3/bd_0834_psr_aclk1_0_board.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_3/bd_0834_psr_aclk1_0.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/ooc.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/constraints/m3_for_arty_a7_mig_7series_0_2.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/constraints/m3_for_arty_a7_mig_7series_0_2_ooc.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_Vertical_Projection_0_0/src/vpro_ram/vpro_ram_ooc.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_Vertical_Projection8_0_0/src/vp_ram/vp_ram_ooc.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_gpio_0_0/m3_for_arty_a7_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_gpio_0_0/m3_for_arty_a7_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_gpio_0_0/m3_for_arty_a7_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_digital_recognition_0_0/src/digital_ram/digital_ram_ooc.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_digital_recognition_0_4/src/digital_ram/digital_ram_ooc.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_digital_recognition_0_3/src/digital_ram/digital_ram_ooc.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_digital_recognition_0_2/src/digital_ram/digital_ram_ooc.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_digital_recognition_0_1/src/digital_ram/digital_ram_ooc.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_gpio_0_2/m3_for_arty_a7_axi_gpio_0_2_board.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_gpio_0_2/m3_for_arty_a7_axi_gpio_0_2_ooc.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_gpio_0_2/m3_for_arty_a7_axi_gpio_0_2.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_quad_spi_1_0/m3_for_arty_a7_axi_quad_spi_1_0_board.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_quad_spi_1_0/m3_for_arty_a7_axi_quad_spi_1_0.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_quad_spi_1_0/m3_for_arty_a7_axi_quad_spi_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_quad_spi_1_0/m3_for_arty_a7_axi_quad_spi_1_0_clocks.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_binary_image_etch_0_2/src/img_ram/img_ram_ooc.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_binary_image_swell_0_2/src/img_ram/img_ram_ooc.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_binary_image_etch_0_1/src/img_ram/img_ram_ooc.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_binary_image_etch_1_2/src/img_ram/img_ram_ooc.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_auto_pc_11/m3_for_arty_a7_auto_pc_11_ooc.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_auto_pc_10/m3_for_arty_a7_auto_pc_10_ooc.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_auto_pc_9/m3_for_arty_a7_auto_pc_9_ooc.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_auto_pc_8/m3_for_arty_a7_auto_pc_8_ooc.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_auto_pc_7/m3_for_arty_a7_auto_pc_7_ooc.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_auto_pc_6/m3_for_arty_a7_auto_pc_6_ooc.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_auto_pc_5/m3_for_arty_a7_auto_pc_5_ooc.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_auto_pc_4/m3_for_arty_a7_auto_pc_4_ooc.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_auto_pc_3/m3_for_arty_a7_auto_pc_3_ooc.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_auto_pc_2/m3_for_arty_a7_auto_pc_2_ooc.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_auto_pc_1/m3_for_arty_a7_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_auto_pc_0/m3_for_arty_a7_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_auto_pc_12/m3_for_arty_a7_auto_pc_12_ooc.xdc]
set_property used_in_implementation false [get_files -all V:/hardware/m3_for_arty_a7/block_diagram/m3_for_arty_a7_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc V:/hardware/m3_for_arty_a7/constraints/m3_for_arty_a7.xdc
set_property used_in_implementation false [get_files V:/hardware/m3_for_arty_a7/constraints/m3_for_arty_a7.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top m3_for_arty_a7_wrapper -part xc7a100tcsg324-1 -fanout_limit 400 -fsm_extraction one_hot -keep_equivalent_registers -resource_sharing off -no_lc -shreg_min_size 5


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef m3_for_arty_a7_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file m3_for_arty_a7_wrapper_utilization_synth.rpt -pb m3_for_arty_a7_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
