#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2018.2 (64-bit)
#
# Filename    : m3_for_arty_a7.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Wed Jul 17 00:27:34 +0800 2019
# SW Build 2258646 on Thu Jun 14 20:03:12 MDT 2018
#
# Copyright 1986-2018 Xilinx, Inc. All Rights Reserved. 
#
# usage: m3_for_arty_a7.sh [-help]
# usage: m3_for_arty_a7.sh [-lib_map_path]
# usage: m3_for_arty_a7.sh [-noclean_files]
# usage: m3_for_arty_a7.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'm3_for_arty_a7.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xilinx_vip xil_defaultlib xpm blk_mem_gen_v8_3_6 axi_bram_ctrl_v4_0_14 axi_lite_ipif_v3_0_4 lib_cdc_v1_0_2 interrupt_control_v3_1_4 axi_gpio_v2_0_19 dist_mem_gen_v8_0_12 lib_pkg_v1_0_2 lib_srl_fifo_v1_0_2 fifo_generator_v13_2_2 lib_fifo_v1_0_11 axi_quad_spi_v3_2_16 axi_uartlite_v2_0_21 blk_mem_gen_v8_4_1 xlconcat_v2_1_1 xlconstant_v1_1_5 generic_baseblocks_v2_1_0 axi_data_fifo_v2_1_16 axi_infrastructure_v1_1_0 axi_register_slice_v2_1_17 axi_protocol_converter_v2_1_17 axi_crossbar_v2_1_18 proc_sys_reset_v5_0_12 util_vector_logic_v2_0_1 v_vid_in_axi4s_v4_0_8 v_tc_v6_1_12 v_axi4s_vid_out_v4_0_9 lib_bmg_v1_0_10 axi_datamover_v5_1_19 axi_vdma_v6_3_5 smartconnect_v1_0)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "m3_for_arty_a7.sh - Script generated by export_simulation (Vivado v2018.2 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../../block_diagram/ipshared/6b77/rtl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b65a" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/f90c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "D:/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "D:/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "D:/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "D:/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "D:/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "D:/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "D:/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "D:/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "D:/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../../block_diagram/ipshared/6b77/rtl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b65a" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/f90c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "D:/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "D:/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "D:/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "D:/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work blk_mem_gen_v8_3_6 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../block_diagram/ipshared/6b77/rtl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b65a" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/f90c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../../block_diagram/ipshared/2751/simulation/blk_mem_gen_v8_3.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_bram_ctrl_v4_0_14 $vhdlan_opts \
    "$ref_dir/../../../../../block_diagram/ipshared/6db1/hdl/axi_bram_ctrl_v4_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_axi_bram_ctrl_0_0/sim/m3_for_arty_a7_axi_bram_ctrl_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../../block_diagram/ipshared/cced/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../../block_diagram/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work interrupt_control_v3_1_4 $vhdlan_opts \
    "$ref_dir/../../../../../block_diagram/ipshared/8e66/hdl/interrupt_control_v3_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_gpio_v2_0_19 $vhdlan_opts \
    "$ref_dir/../../../../../block_diagram/ipshared/c193/hdl/axi_gpio_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_axi_gpio_1_0/sim/m3_for_arty_a7_axi_gpio_1_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work dist_mem_gen_v8_0_12 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../block_diagram/ipshared/6b77/rtl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b65a" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/f90c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../../block_diagram/ipshared/d46a/simulation/dist_mem_gen_v8_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../../block_diagram/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_srl_fifo_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../../block_diagram/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../block_diagram/ipshared/6b77/rtl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b65a" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/f90c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../../block_diagram/ipshared/7aff/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_2 $vhdlan_opts \
    "$ref_dir/../../../../../block_diagram/ipshared/7aff/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../block_diagram/ipshared/6b77/rtl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b65a" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/f90c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../../block_diagram/ipshared/7aff/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_fifo_v1_0_11 $vhdlan_opts \
    "$ref_dir/../../../../../block_diagram/ipshared/6078/hdl/lib_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_quad_spi_v3_2_16 $vhdlan_opts \
    "$ref_dir/../../../../../block_diagram/ipshared/92ac/hdl/axi_quad_spi_v3_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_axi_quad_spi_0_0/sim/m3_for_arty_a7_axi_quad_spi_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_uartlite_v2_0_21 $vhdlan_opts \
    "$ref_dir/../../../../../block_diagram/ipshared/a15e/hdl/axi_uartlite_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_axi_uartlite_0_0/sim/m3_for_arty_a7_axi_uartlite_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work blk_mem_gen_v8_4_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../block_diagram/ipshared/6b77/rtl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b65a" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/f90c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../../block_diagram/ipshared/67d8/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../block_diagram/ipshared/6b77/rtl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b65a" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/f90c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_blk_mem_gen_0_0/sim/m3_for_arty_a7_blk_mem_gen_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconcat_v2_1_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../block_diagram/ipshared/6b77/rtl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b65a" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/f90c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../../block_diagram/ipshared/2f66/hdl/xlconcat_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../block_diagram/ipshared/6b77/rtl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b65a" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/f90c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_xlconcat_0_0/sim/m3_for_arty_a7_xlconcat_0_0.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_xlconcat_1_0/sim/m3_for_arty_a7_xlconcat_1_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconstant_v1_1_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../block_diagram/ipshared/6b77/rtl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b65a" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/f90c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../../block_diagram/ipshared/f1c3/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../block_diagram/ipshared/6b77/rtl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b65a" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/f90c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_xlconstant_1_0/sim/m3_for_arty_a7_xlconstant_1_0.v" \
    "$ref_dir/../../../../../block_diagram/ipshared/6b77/rtl/cm3_dap_ahb_ap.v" \
    "$ref_dir/../../../../../block_diagram/ipshared/6b77/rtl/cm3_wic.v" \
    "$ref_dir/../../../../../block_diagram/ipshared/6b77/rtl/cm3_nvic.v" \
    "$ref_dir/../../../../../block_diagram/ipshared/6b77/rtl/cm3_dwt.v" \
    "$ref_dir/../../../../../block_diagram/ipshared/6b77/rtl/AhbToAxi.v" \
    "$ref_dir/../../../../../block_diagram/ipshared/6b77/rtl/cm3_mpu.v" \
    "$ref_dir/../../../../../block_diagram/ipshared/6b77/rtl/cm3_bus_matrix.v" \
    "$ref_dir/../../../../../block_diagram/ipshared/6b77/rtl/models.v" \
    "$ref_dir/../../../../../block_diagram/ipshared/6b77/rtl/cmsdk.v" \
    "$ref_dir/../../../../../block_diagram/ipshared/6b77/rtl/cm3_tpiu.v" \
    "$ref_dir/../../../../../block_diagram/ipshared/6b77/rtl/dapswjdp.v" \
    "$ref_dir/../../../../../block_diagram/ipshared/6b77/rtl/cm3_fpb.v" \
    "$ref_dir/../../../../../block_diagram/ipshared/6b77/rtl/cm3_dpu.v" \
    "$ref_dir/../../../../../block_diagram/ipshared/6b77/rtl/cm3_itm.v" \
    "$ref_dir/../../../../../block_diagram/ipshared/6b77/rtl/cm3_etm.v" \
    "$ref_dir/../../../../../block_diagram/ipshared/6b77/rtl/cortexm3.v" \
    "$ref_dir/../../../../../block_diagram/ipshared/6b77/rtl/cortexm3_integration.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_Cortex_M3_0_0/sim/m3_for_arty_a7_Cortex_M3_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_axi_single_spi_0_0/sim/m3_for_arty_a7_axi_single_spi_0_0.vhd" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_axi_quad_spi_0_1/sim/m3_for_arty_a7_axi_quad_spi_0_1.vhd" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_axi_xip_quad_spi_0_0/sim/m3_for_arty_a7_axi_xip_quad_spi_0_0.vhd" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_axi_gpio_0_1/sim/m3_for_arty_a7_axi_gpio_0_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../block_diagram/ipshared/6b77/rtl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b65a" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/f90c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../../block_diagram/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_16 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../block_diagram/ipshared/6b77/rtl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b65a" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/f90c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../../block_diagram/ipshared/247d/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../block_diagram/ipshared/6b77/rtl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b65a" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/f90c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../../block_diagram/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_17 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../block_diagram/ipshared/6b77/rtl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b65a" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/f90c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../../block_diagram/ipshared/6020/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_converter_v2_1_17 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../block_diagram/ipshared/6b77/rtl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b65a" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/f90c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../../block_diagram/ipshared/ccfb/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../block_diagram/ipshared/6b77/rtl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b65a" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/f90c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_axi_protocol_convert_0_0/sim/m3_for_arty_a7_axi_protocol_convert_0_0.v" \
    "$ref_dir/../../../../../block_diagram/ipshared/5fe9/DAPLink_to_Arty_shield.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_DAPLink_to_Arty_shield_0_0/sim/m3_for_arty_a7_DAPLink_to_Arty_shield_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_18 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../block_diagram/ipshared/6b77/rtl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b65a" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/f90c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../../block_diagram/ipshared/15a3/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../block_diagram/ipshared/6b77/rtl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b65a" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/f90c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_xbar_0/sim/m3_for_arty_a7_xbar_0.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_xbar_1/sim/m3_for_arty_a7_xbar_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work proc_sys_reset_v5_0_12 $vhdlan_opts \
    "$ref_dir/../../../../../block_diagram/ipshared/f86a/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_proc_sys_reset_DAPLink_0/sim/m3_for_arty_a7_proc_sys_reset_DAPLink_0.vhd" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_proc_sys_reset_base_0/sim/m3_for_arty_a7_proc_sys_reset_base_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work util_vector_logic_v2_0_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../block_diagram/ipshared/6b77/rtl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b65a" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/f90c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../../block_diagram/ipshared/2137/hdl/util_vector_logic_v2_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../block_diagram/ipshared/6b77/rtl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b65a" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/f90c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_i_interconnect_aresetn_0/sim/m3_for_arty_a7_i_interconnect_aresetn_0.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_i_peripheral_aresetn1_0/sim/m3_for_arty_a7_i_peripheral_aresetn1_0.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_i_sysresetn_or_0/sim/m3_for_arty_a7_i_sysresetn_or_0.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_i_inv_dbgresetn_0/sim/m3_for_arty_a7_i_inv_dbgresetn_0.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_i_inv_sysresetn1_0/sim/m3_for_arty_a7_i_inv_sysresetn1_0.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_clk_wiz_0_0/m3_for_arty_a7_clk_wiz_0_0_clk_wiz.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_clk_wiz_0_0/m3_for_arty_a7_clk_wiz_0_0.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_xlconstant_1_1/sim/m3_for_arty_a7_xlconstant_1_1.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work v_vid_in_axi4s_v4_0_8 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../block_diagram/ipshared/6b77/rtl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b65a" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/f90c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../../block_diagram/ipshared/d987/hdl/v_vid_in_axi4s_v4_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../block_diagram/ipshared/6b77/rtl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b65a" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/f90c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_v_vid_in_axi4s_0_0/sim/m3_for_arty_a7_v_vid_in_axi4s_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work v_tc_v6_1_12 $vhdlan_opts \
    "$ref_dir/../../../../../block_diagram/ipshared/6694/hdl/v_tc_v6_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work v_axi4s_vid_out_v4_0_9 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../block_diagram/ipshared/6b77/rtl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b65a" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/f90c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../../block_diagram/ipshared/9a07/hdl/v_axi4s_vid_out_v4_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../block_diagram/ipshared/6b77/rtl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b65a" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/f90c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_v_axi4s_vid_out_0_0/sim/m3_for_arty_a7_v_axi4s_vid_out_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_bmg_v1_0_10 $vhdlan_opts \
    "$ref_dir/../../../../../block_diagram/ipshared/9340/hdl/lib_bmg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_datamover_v5_1_19 $vhdlan_opts \
    "$ref_dir/../../../../../block_diagram/ipshared/ec8a/hdl/axi_datamover_v5_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_vdma_v6_3_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../block_diagram/ipshared/6b77/rtl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b65a" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/f90c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../../block_diagram/ipshared/b37e/hdl/axi_vdma_v6_3_rfs.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_vdma_v6_3_5 $vhdlan_opts \
    "$ref_dir/../../../../../block_diagram/ipshared/b37e/hdl/axi_vdma_v6_3_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_axi_vdma_0_0/sim/m3_for_arty_a7_axi_vdma_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../block_diagram/ipshared/6b77/rtl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b65a" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/f90c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_OV_Sensor_ML_2_1/sim/m3_for_arty_a7_OV_Sensor_ML_2_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_v_tc_0_0/sim/m3_for_arty_a7_v_tc_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../block_diagram/ipshared/6b77/rtl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b65a" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/f90c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_xlconstant_0_0/sim/m3_for_arty_a7_xlconstant_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_proc_sys_reset_0_0/sim/m3_for_arty_a7_proc_sys_reset_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../block_diagram/ipshared/6b77/rtl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b65a" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/f90c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/sim/bd_0834.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../../block_diagram/ipshared/6b77/rtl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b65a" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/f90c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../../block_diagram/ipshared/5bb9/hdl/sc_util_v1_0_vl_rfs.sv" \
    "$ref_dir/../../../../../block_diagram/ipshared/5160/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../../block_diagram/ipshared/6b77/rtl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b65a" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/f90c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_12/sim/bd_0834_s00a2s_0.sv" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_18/sim/bd_0834_s01a2s_0.sv" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_25/sim/bd_0834_s02a2s_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../../block_diagram/ipshared/6b77/rtl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b65a" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/f90c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../../block_diagram/ipshared/acc2/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../../block_diagram/ipshared/6b77/rtl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b65a" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/f90c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_31/sim/bd_0834_m00s2a_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../../block_diagram/ipshared/6b77/rtl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b65a" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/f90c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../../block_diagram/ipshared/28cb/hdl/sc_exit_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../../block_diagram/ipshared/6b77/rtl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b65a" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/f90c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_37/sim/bd_0834_m00e_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../../block_diagram/ipshared/6b77/rtl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b65a" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/f90c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../../block_diagram/ipshared/f90c/hdl/sc_node_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../../block_diagram/ipshared/6b77/rtl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b65a" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/f90c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_32/sim/bd_0834_m00arn_0.sv" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_33/sim/bd_0834_m00rn_0.sv" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_34/sim/bd_0834_m00awn_0.sv" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_35/sim/bd_0834_m00wn_0.sv" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_36/sim/bd_0834_m00bn_0.sv" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_26/sim/bd_0834_sarn_1.sv" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_27/sim/bd_0834_srn_1.sv" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_28/sim/bd_0834_sawn_1.sv" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_29/sim/bd_0834_swn_1.sv" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_30/sim/bd_0834_sbn_1.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../../block_diagram/ipshared/6b77/rtl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b65a" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/f90c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../../block_diagram/ipshared/afa8/hdl/sc_mmu_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../../block_diagram/ipshared/6b77/rtl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b65a" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/f90c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_22/sim/bd_0834_s02mmu_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../../block_diagram/ipshared/6b77/rtl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b65a" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/f90c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../../block_diagram/ipshared/4521/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../../block_diagram/ipshared/6b77/rtl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b65a" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/f90c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_23/sim/bd_0834_s02tr_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../../block_diagram/ipshared/6b77/rtl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b65a" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/f90c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../../block_diagram/ipshared/d1fc/hdl/sc_si_converter_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../../block_diagram/ipshared/6b77/rtl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b65a" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/f90c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_24/sim/bd_0834_s02sic_0.sv" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_19/sim/bd_0834_sawn_0.sv" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_20/sim/bd_0834_swn_0.sv" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_21/sim/bd_0834_sbn_0.sv" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_15/sim/bd_0834_s01mmu_0.sv" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_16/sim/bd_0834_s01tr_0.sv" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_17/sim/bd_0834_s01sic_0.sv" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_13/sim/bd_0834_sarn_0.sv" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_14/sim/bd_0834_srn_0.sv" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_9/sim/bd_0834_s00mmu_0.sv" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_10/sim/bd_0834_s00tr_0.sv" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_11/sim/bd_0834_s00sic_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../../block_diagram/ipshared/6b77/rtl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b65a" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/f90c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../../block_diagram/ipshared/4e7b/hdl/sc_switchboard_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../../block_diagram/ipshared/6b77/rtl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b65a" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/f90c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_4/sim/bd_0834_arsw_0.sv" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_5/sim/bd_0834_rsw_0.sv" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_6/sim/bd_0834_awsw_0.sv" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_7/sim/bd_0834_wsw_0.sv" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_8/sim/bd_0834_bsw_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../block_diagram/ipshared/6b77/rtl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b65a" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/f90c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_0/sim/bd_0834_one_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_1/sim/bd_0834_psr0_0.vhd" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_2/sim/bd_0834_psr_aclk_0.vhd" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/bd_0/ip/ip_3/sim/bd_0834_psr_aclk1_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../block_diagram/ipshared/6b77/rtl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b65a" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/f90c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_smartconnect_0_0/sim/m3_for_arty_a7_smartconnect_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../../block_diagram/ipshared/69dc/src/rgb2vga.vhd" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_rgb2vga_0_0/sim/m3_for_arty_a7_rgb2vga_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../block_diagram/ipshared/6b77/rtl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b65a" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/f90c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/axi/mig_7series_v4_1_axi_ctrl_addr_decode.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/axi/mig_7series_v4_1_axi_ctrl_read.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/axi/mig_7series_v4_1_axi_ctrl_reg.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/axi/mig_7series_v4_1_axi_ctrl_reg_bank.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/axi/mig_7series_v4_1_axi_ctrl_top.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/axi/mig_7series_v4_1_axi_ctrl_write.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/axi/mig_7series_v4_1_axi_mc.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/axi/mig_7series_v4_1_axi_mc_ar_channel.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/axi/mig_7series_v4_1_axi_mc_aw_channel.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/axi/mig_7series_v4_1_axi_mc_b_channel.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/axi/mig_7series_v4_1_axi_mc_cmd_arbiter.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/axi/mig_7series_v4_1_axi_mc_cmd_fsm.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/axi/mig_7series_v4_1_axi_mc_cmd_translator.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/axi/mig_7series_v4_1_axi_mc_fifo.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/axi/mig_7series_v4_1_axi_mc_incr_cmd.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/axi/mig_7series_v4_1_axi_mc_r_channel.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/axi/mig_7series_v4_1_axi_mc_simple_fifo.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/axi/mig_7series_v4_1_axi_mc_wrap_cmd.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/axi/mig_7series_v4_1_axi_mc_wr_cmd_fsm.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/axi/mig_7series_v4_1_axi_mc_w_channel.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/axi/mig_7series_v4_1_ddr_axic_register_slice.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/axi/mig_7series_v4_1_ddr_axi_register_slice.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/axi/mig_7series_v4_1_ddr_axi_upsizer.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/axi/mig_7series_v4_1_ddr_a_upsizer.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/axi/mig_7series_v4_1_ddr_carry_and.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/axi/mig_7series_v4_1_ddr_carry_latch_and.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/axi/mig_7series_v4_1_ddr_carry_latch_or.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/axi/mig_7series_v4_1_ddr_carry_or.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/axi/mig_7series_v4_1_ddr_command_fifo.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/axi/mig_7series_v4_1_ddr_comparator.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/axi/mig_7series_v4_1_ddr_comparator_sel.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/axi/mig_7series_v4_1_ddr_comparator_sel_static.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/axi/mig_7series_v4_1_ddr_r_upsizer.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/axi/mig_7series_v4_1_ddr_w_upsizer.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/clocking/mig_7series_v4_1_clk_ibuf.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/clocking/mig_7series_v4_1_infrastructure.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/clocking/mig_7series_v4_1_iodelay_ctrl.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/clocking/mig_7series_v4_1_tempmon.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/controller/mig_7series_v4_1_arb_mux.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/controller/mig_7series_v4_1_arb_row_col.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/controller/mig_7series_v4_1_arb_select.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/controller/mig_7series_v4_1_bank_cntrl.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/controller/mig_7series_v4_1_bank_common.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/controller/mig_7series_v4_1_bank_compare.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/controller/mig_7series_v4_1_bank_mach.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/controller/mig_7series_v4_1_bank_queue.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/controller/mig_7series_v4_1_bank_state.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/controller/mig_7series_v4_1_col_mach.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/controller/mig_7series_v4_1_mc.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/controller/mig_7series_v4_1_rank_cntrl.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/controller/mig_7series_v4_1_rank_common.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/controller/mig_7series_v4_1_rank_mach.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/controller/mig_7series_v4_1_round_robin_arb.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/ecc/mig_7series_v4_1_ecc_buf.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/ecc/mig_7series_v4_1_ecc_dec_fix.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/ecc/mig_7series_v4_1_ecc_gen.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/ecc/mig_7series_v4_1_ecc_merge_enc.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/ecc/mig_7series_v4_1_fi_xor.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/ip_top/mig_7series_v4_1_memc_ui_top_axi.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/ip_top/mig_7series_v4_1_mem_intfc.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/phy/mig_7series_v4_1_ddr_byte_group_io.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/phy/mig_7series_v4_1_ddr_byte_lane.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/phy/mig_7series_v4_1_ddr_calib_top.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/phy/mig_7series_v4_1_ddr_if_post_fifo.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/phy/mig_7series_v4_1_ddr_mc_phy.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/phy/mig_7series_v4_1_ddr_mc_phy_wrapper.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/phy/mig_7series_v4_1_ddr_of_pre_fifo.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_4lanes.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_ck_addr_cmd_delay.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_dqs_found_cal.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_dqs_found_cal_hr.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_init.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_ocd_cntlr.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_ocd_data.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_ocd_edge.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_ocd_lim.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_ocd_mux.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_ocd_po_cntlr.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_ocd_samp.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_oclkdelay_cal.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_prbs_rdlvl.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_rdlvl.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_tempmon.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_top.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_wrcal.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_wrlvl.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_wrlvl_off_delay.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/phy/mig_7series_v4_1_ddr_prbs_gen.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/phy/mig_7series_v4_1_poc_cc.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/phy/mig_7series_v4_1_poc_edge_store.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/phy/mig_7series_v4_1_poc_meta.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/phy/mig_7series_v4_1_poc_pd.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/phy/mig_7series_v4_1_poc_tap_base.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/phy/mig_7series_v4_1_poc_top.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/ui/mig_7series_v4_1_ui_cmd.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/ui/mig_7series_v4_1_ui_rd_data.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/ui/mig_7series_v4_1_ui_top.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/ui/mig_7series_v4_1_ui_wr_data.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/m3_for_arty_a7_mig_7series_0_2_mig_sim.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_mig_7series_0_2/m3_for_arty_a7_mig_7series_0_2/user_design/rtl/m3_for_arty_a7_mig_7series_0_2.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_xlconstant_0_2/sim/m3_for_arty_a7_xlconstant_0_2.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_I2C_OV5640_Init_RGB5_0_0/sim/m3_for_arty_a7_I2C_OV5640_Init_RGB5_0_0.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_rgb_change_0_0/sim/m3_for_arty_a7_rgb_change_0_0.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_sync_change_0_0/sim/m3_for_arty_a7_sync_change_0_0.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_HVcount_0_0/sim/m3_for_arty_a7_HVcount_0_0.v" \
    "$ref_dir/../../../../../block_diagram/ipshared/51e6/sim/rgb2ycbcr.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_rgb2ycbcr_0_0/sim/m3_for_arty_a7_rgb2ycbcr_0_0.v" \
    "$ref_dir/../../../../../block_diagram/ipshared/0817/sim/car_id.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_car_id_0_0/sim/m3_for_arty_a7_car_id_0_0.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_Vertical_Projection_0_0/src/vpro_ram/sim/vpro_ram.v" \
    "$ref_dir/../../../../../block_diagram/ipshared/8247/sim/Vertical_Projection.v" \
    "$ref_dir/../../../../../block_diagram/ipshared/8247/src/Vertical_Projection.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_Vertical_Projection_0_0/sim/m3_for_arty_a7_Vertical_Projection_0_0.v" \
    "$ref_dir/../../../../../block_diagram/ipshared/4ed8/sim/capture_lpr.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_capture_lpr_0_0/sim/m3_for_arty_a7_capture_lpr_0_0.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_rgb2ycbcr_1_0/sim/m3_for_arty_a7_rgb2ycbcr_1_0.v" \
    "$ref_dir/../../../../../block_diagram/ipshared/3a98/sim/ycbcr_location.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_ycbcr_location_0_0/sim/m3_for_arty_a7_ycbcr_location_0_0.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_HVcount_1_0/sim/m3_for_arty_a7_HVcount_1_0.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_Vertical_Projection8_0_0/src/vp_ram/sim/vp_ram.v" \
    "$ref_dir/../../../../../block_diagram/ipshared/4d03/sim/Vertical_Projection8.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_Vertical_Projection8_0_0/sim/m3_for_arty_a7_Vertical_Projection8_0_0.v" \
    "$ref_dir/../../../../../block_diagram/ipshared/ba5c/sim/display.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_display_0_0/sim/m3_for_arty_a7_display_0_0.v" \
    "$ref_dir/../../../../../block_diagram/ipshared/aae4/sim/rgb_mux.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_rgb_mux_0_0/sim/m3_for_arty_a7_rgb_mux_0_0.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_sync_change_1_0/sim/m3_for_arty_a7_sync_change_1_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_axi_gpio_0_0/sim/m3_for_arty_a7_axi_gpio_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../block_diagram/ipshared/6b77/rtl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b65a" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/f90c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_capture_single_0_1/sim/m3_for_arty_a7_capture_single_0_1.v" \
    "$ref_dir/../../../../../block_diagram/ipshared/21c7/hdl/char_recongize_5thing_v1_0_S00_AXI.v" \
    "$ref_dir/../../../../../block_diagram/ipshared/21c7/hdl/char_recongize_5thing_v1_0.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_char_recongize_5thing_0_0/sim/m3_for_arty_a7_char_recongize_5thing_0_0.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_digital_recognition_0_0/src/digital_ram/sim/digital_ram.v" \
    "$ref_dir/../../../../../block_diagram/ipshared/c429/sim/fifo_y.v" \
    "$ref_dir/../../../../../block_diagram/ipshared/c429/sim/digital_recognition.v" \
    "$ref_dir/../../../../../block_diagram/ipshared/c429/src/digital_recognition.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_digital_recognition_0_0/sim/m3_for_arty_a7_digital_recognition_0_0.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_xlconcat_0_1/sim/m3_for_arty_a7_xlconcat_0_1.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_display_lpr_boundary_0_0/sim/m3_for_arty_a7_display_lpr_boundary_0_0.v" \
    "$ref_dir/../../../../../block_diagram/ipshared/a4d2/hdl/send_line_data_v1_0_S00_AXI.v" \
    "$ref_dir/../../../../../block_diagram/ipshared/a4d2/hdl/send_line_data_v1_0.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_send_line_data_0_0/sim/m3_for_arty_a7_send_line_data_0_0.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_capture_single_0_4/sim/m3_for_arty_a7_capture_single_0_4.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_digital_recognition_0_4/sim/m3_for_arty_a7_digital_recognition_0_4.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_xlconcat_0_5/sim/m3_for_arty_a7_xlconcat_0_5.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_capture_single_0_3/sim/m3_for_arty_a7_capture_single_0_3.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_digital_recognition_0_3/sim/m3_for_arty_a7_digital_recognition_0_3.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_xlconcat_0_4/sim/m3_for_arty_a7_xlconcat_0_4.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_capture_single_0_2/sim/m3_for_arty_a7_capture_single_0_2.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_digital_recognition_0_2/sim/m3_for_arty_a7_digital_recognition_0_2.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_xlconcat_0_3/sim/m3_for_arty_a7_xlconcat_0_3.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_capture_single_0_0/sim/m3_for_arty_a7_capture_single_0_0.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_digital_recognition_0_1/sim/m3_for_arty_a7_digital_recognition_0_1.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_xlconcat_0_2/sim/m3_for_arty_a7_xlconcat_0_2.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_axi_gpio_0_2/sim/m3_for_arty_a7_axi_gpio_0_2.vhd" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_axi_quad_spi_1_0/sim/m3_for_arty_a7_axi_quad_spi_1_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../block_diagram/ipshared/6b77/rtl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b65a" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/f90c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../../block_diagram/sim/m3_for_arty_a7.v" \
    "$ref_dir/../../../../../block_diagram/ipshared/33d1/hdl/Hcount_Send_v1_0_S00_AXI.v" \
    "$ref_dir/../../../../../block_diagram/ipshared/33d1/hdl/Hcount_Send_v1_0.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_Hcount_Send_0_0/sim/m3_for_arty_a7_Hcount_Send_0_0.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_binary_image_etch_0_2/src/img_ram/sim/img_ram.v" \
    "$ref_dir/../../../../../block_diagram/ipshared/5540/sim/fifo_linebuffer.v" \
    "$ref_dir/../../../../../block_diagram/ipshared/5540/sim/line.v" \
    "$ref_dir/../../../../../block_diagram/ipshared/5540/sim/linebuffer.v" \
    "$ref_dir/../../../../../block_diagram/ipshared/5540/sim/binary_image_etch.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_binary_image_etch_0_2/sim/m3_for_arty_a7_binary_image_etch_0_2.v" \
    "$ref_dir/../../../../../block_diagram/ipshared/2794/sim/binary_image_swell.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_binary_image_swell_0_2/sim/m3_for_arty_a7_binary_image_swell_0_2.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_binary_image_etch_0_1/sim/m3_for_arty_a7_binary_image_etch_0_1.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_binary_image_etch_1_2/sim/m3_for_arty_a7_binary_image_etch_1_2.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_auto_pc_11/sim/m3_for_arty_a7_auto_pc_11.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_auto_pc_10/sim/m3_for_arty_a7_auto_pc_10.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_auto_pc_9/sim/m3_for_arty_a7_auto_pc_9.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_auto_pc_8/sim/m3_for_arty_a7_auto_pc_8.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_auto_pc_7/sim/m3_for_arty_a7_auto_pc_7.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_auto_pc_6/sim/m3_for_arty_a7_auto_pc_6.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_auto_pc_5/sim/m3_for_arty_a7_auto_pc_5.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_auto_pc_4/sim/m3_for_arty_a7_auto_pc_4.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_auto_pc_3/sim/m3_for_arty_a7_auto_pc_3.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_auto_pc_2/sim/m3_for_arty_a7_auto_pc_2.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_auto_pc_1/sim/m3_for_arty_a7_auto_pc_1.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_auto_pc_0/sim/m3_for_arty_a7_auto_pc_0.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_auto_pc_12/sim/m3_for_arty_a7_auto_pc_12.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.m3_for_arty_a7 xil_defaultlib.glbl -o m3_for_arty_a7_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./m3_for_arty_a7_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./m3_for_arty_a7.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key m3_for_arty_a7_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc m3_for_arty_a7_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./m3_for_arty_a7.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: m3_for_arty_a7.sh [-help]\n\
Usage: m3_for_arty_a7.sh [-lib_map_path]\n\
Usage: m3_for_arty_a7.sh [-reset_run]\n\
Usage: m3_for_arty_a7.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
